apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-proxy-addon-agent
  namespace: {{ .Release.Namespace }}
{{ if eq .Values.installMode "Hosted" }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{ end }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
