{{ if .Values.includeStaticProxyAgentSecret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: cluster-proxy-open-cluster-management.io-proxy-agent-signer-client-cert
data:
  "tls.crt": {{ .Values.staticProxyAgentSecretCert }}
  "tls.key": {{ .Values.staticProxyAgentSecretKey }}
{{ end }}
