apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: cluster-proxy-ca
{{ if eq .Values.installMode "Hosted" }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{ end }}
data:
  "ca.crt": {{ .Values.base64EncodedCAData }}
