apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.clusterName }}
spec:
  type: ExternalName
  externalName: kubernetes.default.{{ .Values.serviceDomain }}
