apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-proxy-dns-override
  namespace: {{ .Release.Namespace }}
data:
  Corefile: |
    .:53 {
      errors
      log
      rewrite name local-cluster kubernetes.default.{{ .Values.serviceDomain }}
      rewrite name local-cluster.open-cluster-management-cluster-proxy kubernetes.default.{{ .Values.serviceDomain }}
      rewrite name local-cluster.open-cluster-management-cluster-proxy.svc.cluster.local kubernetes.default.{{ .Values.serviceDomain }}
      forward . /etc/resolv.conf
      cache 30
      reload
    }
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: {{ .Release.Namespace }}
#   name: {{ .Values.clusterName }}
# spec:
#   type: ExternalName
#   externalName: kubernetes.default.{{ .Values.serviceDomain }}