{{ if .Values.enableKubeApiProxy }}
{{ if eq .Values.installMode "Hosted" }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.clusterName }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
spec:
  type: ClusterIP
  selector:
    open-cluster-management.io/addon: cluster-proxy
    proxy.open-cluster-management.io/component-name: proxy-agent
  ports:
    - name: https
      port: 443
      targetPort: 8443
{{ else }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.clusterName }}
spec:
  type: ExternalName
  externalName: kubernetes.default.{{ .Values.serviceDomain }}
{{ end }}
{{ end }}
