apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: cluster-proxy
{{ if eq .Values.installMode "Hosted" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: cluster-proxy
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{ end }}
