apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:cluster-proxy:addon-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:cluster-proxy:addon-manager
subjects:
  - kind: ServiceAccount
    name: cluster-proxy
    namespace: {{ .Release.Namespace }}
