clusterName: loopback

agentDeploymentName: cluster-proxy-proxy-agent

includeNamespaceCreation: false

# Image registry
registry: quay.io/open-cluster-management

# Image of the cluster-gateway instances
image: cluster-proxy

proxyAgentImage: quay.io/open-cluster-management/cluster-proxy:latest
proxyAgentImagePullSecrets: []

# Number of replicas
replicas: 1

spokeAddonNamespace: "open-cluster-management-cluster-proxy"
additionalProxyAgentArgs: []

agentDeploymentAnnotations: {}

addonAgentArgs: []

serviceEntryPoint: ""
serviceEntryPointPort: 8091

base64EncodedCAData: Zm9vCg==

serviceDomain: ""

tolerations: []

nodeSelector: {}
proxyConfig:
  HTTP_PROXY: null
  HTTPS_PROXY: null
  NO_PROXY: null

global:
  resourceRequirements:
  - containerIDRegex: ^.+:.+:.+$
    resources:
      requests:
        memory: 100Mi
        cpu: 200m
      limits:
        memory: 200Mi
        cpu: 300m
