clusterName: loopback

agentDeploymentName: cluster-proxy-proxy-agent

includeNamespaceCreation: false

# Image registry
registry: quay.io/open-cluster-management

# Image of the cluster-gateway instances
image: cluster-proxy

# Image tag
tag: v0.1.3

proxyAgentImage: quay.io/open-cluster-management/cluster-proxy:v0.1.4
proxyAgentImagePullSecrets: []

# Number of replicas
replicas: 1

spokeAddonNamespace: "open-cluster-management-cluster-proxy"
additionalProxyAgentArgs: []

agentDeploymentAnnotations: {}

addonAgentArgs: []

serviceEntryPoint: ""
serviceEntryPointPort: 8091

base64EncodedCAData: Zm9vCg==

serviceDomain: ""