clusterName: loopback
installMode: Default

agentDeploymentName: cluster-proxy-proxy-agent

includeNamespaceCreation: false

# Image registry
registry: quay.io/open-cluster-management

# Image of the cluster-gateway instances
image: cluster-proxy

proxyAgentImage: quay.io/open-cluster-management/cluster-proxy:latest
proxyAgentImagePullSecrets: []

# Number of replicas
replicas: 1

spokeAddonNamespace: "open-cluster-management-cluster-proxy"
additionalProxyAgentArgs: []
additionalServiceProxyArgs: []

externalManagedKubeConfigSecretNamespace: ""
externalManagedKubeConfigSecretName: external-managed-kubeconfig
managedKubeConfigSecret: cluster-proxy-managed-kubeconfig
managedKubeConfigTokenExpiration: 24h
managedKubeConfigRefreshBefore: 1h
managedKubeConfigSyncInterval: 5m
hostedServiceProxyMode: Disabled
serviceRelayName: cluster-proxy-service-relay
serviceRelayPort: 7444

agentDeploymentAnnotations: {}

addonAgentArgs: []

serviceEntryPoint: ""
serviceEntryPointPort: 8091

base64EncodedCAData: Zm9vCg==

serviceDomain: ""

nodeSelector: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

proxyConfig:
  HTTP_PROXY: null
  HTTPS_PROXY: null
  NO_PROXY: null

enableImpersonation: "true"

global:
  resourceRequirements: []
