name: ChartUpload

permissions:
  contents: read

on:
  release:
    types: [published]

env:
  # Common versions
  GO_VERSION: '1.22'
  GO_REQUIRED_MIN_VERSION: ''
  GITHUB_REF: ${{ github.ref }}
  CHART_NAME: 'cluster-proxy'

jobs:
  env:
    name: prepare release env
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: get release version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: get major release version
        run: |
          echo "MAJOR_RELEASE_VERSION=${RELEASE_VERSION%.*}" >> $GITHUB_ENV
          echo "TRIMED_RELEASE_VERSION=${RELEASE_VERSION#v}" >> $GITHUB_ENV
      - name: verify chart version
        run: |
          cat ./charts/cluster-proxy/Chart.yaml  | grep -q 'version: ${{ env.TRIMED_RELEASE_VERSION }}'
    outputs:
      MAJOR_RELEASE_VERSION: ${{ env.MAJOR_RELEASE_VERSION }}
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      TRIMED_RELEASE_VERSION: ${{ env.TRIMED_RELEASE_VERSION }}
  upload:
    name: upload
    runs-on: ubuntu-latest
    needs: [ env ]
    permissions:
      contents: write
    steps:
      - name: submit charts to OCM chart repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.OCM_BOT_PAT }}
          script: |
            try {
              const result = await github.rest.actions.createWorkflowDispatch({
                owner:          'open-cluster-management-io',
                repo:           'helm-charts',
                workflow_id:    'download-chart.yml',
                ref: 'main',
                inputs: {
                  repo:         "${{ github.repository }}",
                  version:      "${{ needs.env.outputs.TRIMED_RELEASE_VERSION }}",
                  "chart-name": "${{ env.CHART_NAME }}",
                },
              })
              console.log(result);
            } catch(error) {
              console.error(error);
              core.setFailed(error);
            }
